PublishTools.exe -mode DeleteDirectory --name "../../docs"
PublishTools.exe -mode CopyDirectory --from "build" --to "../../docs"
PublishTools.exe -mode ReplaceInFile --name "../../docs/index.html" --from "{Title}" --to "Olrix Tools"
PublishTools.exe -mode ReplaceInFile --name "../../docs/index.html" --from "{H1}" --to "Olrix Tools"
PublishTools.exe -mode ReplaceInFile --name "../../docs/index.html" --from "{Canonical}" --to "/"
PublishTools.exe -mode ReplaceInFile --name "../../docs/index.html" --from "{Text}" --to "<div><center>Olrix Tools</center></div>"
PublishTools.exe -mode CreatePages --pages "src/app/Routes.ts" --to "../../docs/tools" --source "build/index.html" --url "/tools/"
PublishTools.exe -mode CreateSiteMap --on "../../docs" --url "https://www.olrix.net/"